### ISSUE TITLE
Auslösegeräusch kommt zu früh

### ISSUE THREAD

**Issue by ArloL** [evosec/fotilo#1]
Fix pls

**Comment by dodgex** [comment]
GL HF :D

**Comment by dodgex** [comment]
In [`CamFragment::takePicture`](https://github.com/evosec/fotilo/blob/develop/fotilo-app/src/main/java/de/evosec/fotilo/CamFragment.java#L521):

Der erste Parameter von `camera.takePicture` ist ein [`ShutterCallback`](https://developer.android.com/reference/android/hardware/Camera.ShutterCallback.html) 

aus der JavaDoc von `takePicture`
> The shutter callback occurs after the image is captured. This can be used to trigger a sound to let the user know that image has been captured.

**Comment by ArloL** [comment]
I tried ;)

**Comment by dodgex** [comment]
fixed in #2
